/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Sqlite3_Statement */

#ifndef _Included_pers_zhc_tools_jni_JNI_Sqlite3_Statement
#define _Included_pers_zhc_tools_jni_JNI_Sqlite3_Statement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    bind
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_bind__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    bind
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_bind__JIJ
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    bind
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_bind__JID
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    bindText
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_bindText
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    bindNull
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_bindNull
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    bindBlob
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_bindBlob
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    step
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_step
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_finalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    getCursor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_getCursor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    stepRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_stepRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Statement
 * Method:    getIndexByColumnName
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Statement_getIndexByColumnName
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
