/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_FourierSeries */

#ifndef _Included_pers_zhc_tools_jni_JNI_FourierSeries
#define _Included_pers_zhc_tools_jni_JNI_FourierSeries
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_FourierSeries
 * Method:    calc
 * Signature: (Ljava/util/ArrayList;DILpers/zhc/tools/jni/JNI/FourierSeries/Callback;II)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024FourierSeries_calc
        (JNIEnv *, jclass, jobject, jdouble, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
