/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_JniTest */

#ifndef _Included_pers_zhc_tools_jni_JNI_JniTest
#define _Included_pers_zhc_tools_jni_JNI_JniTest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024JniTest_call
        (JNIEnv *, jclass, jint f);


#ifdef __cplusplus
}
#endif
#endif
