/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_StcFlash_EchoCallback */

#ifndef _Included_pers_zhc_tools_jni_JNI_StcFlash_EchoCallback
#define _Included_pers_zhc_tools_jni_JNI_StcFlash_EchoCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
