/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_FloatingBoard */

#ifndef _Included_pers_zhc_tools_jni_JNI_FloatingBoard
#define _Included_pers_zhc_tools_jni_JNI_FloatingBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_FloatingBoard
 * Method:    floatToByteArray
 * Signature: ([BFI)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024FloatingBoard_floatToByteArray
        (JNIEnv *, jclass, jbyteArray, jfloat, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_FloatingBoard
 * Method:    intToByteArray
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024FloatingBoard_intToByteArray
        (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_FloatingBoard
 * Method:    byteArrayToFloat
 * Signature: ([BI)F
 */
JNIEXPORT jfloat JNICALL Java_pers_zhc_tools_jni_JNI_00024FloatingBoard_byteArrayToFloat
        (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_FloatingBoard
 * Method:    byteArrayToInt
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024FloatingBoard_byteArrayToInt
        (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
