/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Sqlite3_Cursor */

#ifndef _Included_pers_zhc_tools_jni_JNI_Sqlite3_Cursor
#define _Included_pers_zhc_tools_jni_JNI_Sqlite3_Cursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    step
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_step
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    getBlob
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_getBlob
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    getText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_getText
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    getDouble
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_getDouble
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    getLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_getLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3_Cursor
 * Method:    getInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_00024Cursor_getInt
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
