/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_SysInfo */

#ifndef _Included_pers_zhc_tools_jni_JNI_SysInfo
#define _Included_pers_zhc_tools_jni_JNI_SysInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_SysInfo
 * Method:    getUptime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024SysInfo_getUptime
  (JNIEnv *, jclass);

/*
 * Class:     pers_zhc_tools_jni_JNI_SysInfo
 * Method:    getProcessesCount
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_pers_zhc_tools_jni_JNI_00024SysInfo_getProcessesCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
