/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Codecs */

#ifndef _Included_pers_zhc_tools_jni_JNI_Codecs
#define _Included_pers_zhc_tools_jni_JNI_Codecs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Codecs
 * Method:    qmcDecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILpers/zhc/tools/jni/JNI/Codecs/Callback;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Codecs_qmcDecode
        (JNIEnv *, jclass, jstring, jstring, jint, jobject);

/*
 * Class:     pers_zhc_tools_jni_JNI_Codecs
 * Method:    kwmDecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILpers/zhc/tools/jni/JNI/Codecs/Callback;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Codecs_kwmDecode
        (JNIEnv *, jclass, jstring, jstring, jint, jobject);

/*
 * Class:     pers_zhc_tools_jni_JNI_Codecs
 * Method:    Base128_encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILpers/zhc/tools/jni/JNI/Codecs/Callback;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Codecs_Base128_1encode
        (JNIEnv *, jclass, jstring, jstring, jint, jobject);

/*
 * Class:     pers_zhc_tools_jni_JNI_Codecs
 * Method:    Base128_decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILpers/zhc/tools/jni/JNI/Codecs/Callback;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Codecs_Base128_1decode
        (JNIEnv *, jclass, jstring, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
