/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_StcFlash */

#ifndef _Included_pers_zhc_tools_jni_JNI_StcFlash
#define _Included_pers_zhc_tools_jni_JNI_StcFlash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_StcFlash
 * Method:    burn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024StcFlash_burn
  (JNIEnv *, jclass, jstring, jobject jniInterface);

#ifdef __cplusplus
}
#endif
#endif
