/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_JniTest */

#ifndef _Included_pers_zhc_tools_jni_JNI_JniTest
#define _Included_pers_zhc_tools_jni_JNI_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_JniTest
 * Method:    call
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024JniTest_call
        (JNIEnv *, jclass);

/*
 * Class:     pers_zhc_tools_jni_JNI_JniTest
 * Method:    toCall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024JniTest_toCall
        (JNIEnv *, jclass);

/*
 * Class:     pers_zhc_tools_jni_JNI_JniTest
 * Method:    toCall2
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024JniTest_toCall2
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
