/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Sqlite3 */

#ifndef _Included_pers_zhc_tools_jni_JNI_Sqlite3
#define _Included_pers_zhc_tools_jni_JNI_Sqlite3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    exec
 * Signature: (JLjava/lang/String;Lpers/zhc/tools/jni/JNI/Sqlite3/SqliteExecCallback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_exec
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    checkIfCorrupt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_checkIfCorrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    compileStatement
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_compileStatement
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
