/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_MAllocTest */

#ifndef _Included_pers_zhc_tools_jni_JNI_MAllocTest
#define _Included_pers_zhc_tools_jni_JNI_MAllocTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_MAllocTest
 * Method:    alloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024MAllocTest_alloc
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
