/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Char */

#ifndef _Included_pers_zhc_tools_jni_JNI_Char
#define _Included_pers_zhc_tools_jni_JNI_Char
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Char
 * Method:    getUtf8Len
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Char_getUtf8Len
  (JNIEnv *, jclass, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Char
 * Method:    encodeUTF8
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Char_encodeUTF8
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Char
 * Method:    getUtf16Len
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Char_getUtf16Len
  (JNIEnv *, jclass, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Char
 * Method:    encodeUTF16
 * Signature: (I[SI)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Char_encodeUTF16
  (JNIEnv *, jclass, jint, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
