/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Diary */

#ifndef _Included_pers_zhc_tools_jni_JNI_Diary
#define _Included_pers_zhc_tools_jni_JNI_Diary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Diary
 * Method:    myDigest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_zhc_tools_jni_JNI_00024Diary_myDigest
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
