/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_FourierSeries */

#ifndef _Included_pers_zhc_tools_jni_JNI_FourierSeries
#define _Included_pers_zhc_tools_jni_JNI_FourierSeries
#ifdef __cplusplus
extern "C" {
#endif
#undef pers_zhc_tools_jni_JNI_FourierSeries_LINEAR_PATH_EVALUATOR
#define pers_zhc_tools_jni_JNI_FourierSeries_LINEAR_PATH_EVALUATOR 0L
#undef pers_zhc_tools_jni_JNI_FourierSeries_TIME_PATH_EVALUATOR
#define pers_zhc_tools_jni_JNI_FourierSeries_TIME_PATH_EVALUATOR 1L
/*
 * Class:     pers_zhc_tools_jni_JNI_FourierSeries
 * Method:    compute
 * Signature: ([Lpers/zhc/tools/fourierseries/InputPoint;IDIIILpers/zhc/tools/jni/JNI/FourierSeries/Callback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024FourierSeries_compute
  (JNIEnv *, jclass, jobjectArray, jint, jdouble, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
