/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Utf8 */

#ifndef _Included_pers_zhc_tools_jni_JNI_Utf8
#define _Included_pers_zhc_tools_jni_JNI_Utf8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Utf8
 * Method:    getCodepointIterator
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024Utf8_getCodepointIterator
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pers_zhc_tools_jni_JNI_Utf8
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_pers_zhc_tools_jni_JNI_00024Utf8_hasNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Utf8
 * Method:    next
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Utf8_next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Utf8
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Utf8_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Utf8
 * Method:    codepointLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Utf8_codepointLength
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pers_zhc_tools_jni_JNI_Utf8
 * Method:    codepoint2str
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_zhc_tools_jni_JNI_00024Utf8_codepoint2str
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
