/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Email */

#ifndef _Included_pers_zhc_tools_jni_JNI_Email
#define _Included_pers_zhc_tools_jni_JNI_Email
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Email
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Email_send
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jobjectArray, jobjectArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
