/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_JniDemo */

#ifndef _Included_pers_zhc_tools_jni_JNI_JniDemo
#define _Included_pers_zhc_tools_jni_JNI_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_JniDemo
 * Method:    hello
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_zhc_tools_jni_JNI_00024JniDemo_hello
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
