/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Magic */

#ifndef _Included_pers_zhc_tools_jni_JNI_Magic
#define _Included_pers_zhc_tools_jni_JNI_Magic
#ifdef __cplusplus
extern "C" {
#endif
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NONE
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NONE 0L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_DEBUG
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_DEBUG 1L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_SYMLINK
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_SYMLINK 2L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_COMPRESS
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_COMPRESS 4L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_DEVICES
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_DEVICES 8L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_MIME_TYPE
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_MIME_TYPE 16L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_CONTINUE
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_CONTINUE 32L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_CHECK
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_CHECK 64L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_PRESERVE_ATIME
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_PRESERVE_ATIME 128L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_RAW
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_RAW 256L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_ERROR
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_ERROR 512L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_MIME_ENCODING
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_MIME_ENCODING 1024L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_MIME
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_MIME 1040L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_APPLE
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_APPLE 2048L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_EXTENSION
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_EXTENSION 16777216L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_COMPRESS_TRANSP
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_COMPRESS_TRANSP 33554432L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NODESC
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NODESC 16780304L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_COMPRESS
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_COMPRESS 4096L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_TAR
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_TAR 8192L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_SOFT
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_SOFT 16384L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_APPTYPE
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_APPTYPE 32768L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_ELF
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_ELF 65536L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_TEXT
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_TEXT 131072L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_CDF
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_CDF 262144L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_CSV
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_CSV 524288L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_TOKENS
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_TOKENS 1048576L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_ENCODING
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_ENCODING 2097152L
#undef pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_JSON
#define pers_zhc_tools_jni_JNI_Magic_MAGIC_NO_CHECK_JSON 4194304L
/*
 * Class:     pers_zhc_tools_jni_JNI_Magic
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_pers_zhc_tools_jni_JNI_00024Magic_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Magic
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Magic_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     pers_zhc_tools_jni_JNI_Magic
 * Method:    load
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Magic_load
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     pers_zhc_tools_jni_JNI_Magic
 * Method:    setFlag
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Magic_setFlag
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Magic
 * Method:    file
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_zhc_tools_jni_JNI_00024Magic_file
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
