/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_CharUcd */

#ifndef _Included_pers_zhc_tools_jni_JNI_CharUcd
#define _Included_pers_zhc_tools_jni_JNI_CharUcd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_CharUcd
 * Method:    parseXml
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lpers/zhc/tools/jni/JNI/CharUcd/ProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024CharUcd_parseXml
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     pers_zhc_tools_jni_JNI_CharUcd
 * Method:    parseIntermediate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lpers/zhc/tools/jni/JNI/CharUcd/ProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024CharUcd_writeDatabase
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
