/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_tools_pi_PiJNI */

#ifndef _Included_com_zhc_tools_pi_PiJNI
#define _Included_com_zhc_tools_pi_PiJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_tools_pi_PiJNI
 * Method:    gen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zhc_tools_pi_PiJNI_gen
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
