/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_tools_floatingdrawing_JNI */

#ifndef _Included_com_zhc_tools_floatingdrawing_JNI
#define _Included_com_zhc_tools_floatingdrawing_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_tools_floatingdrawing_JNI
 * Method:    mV
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_floatingdrawing_JNI_mG
        (JNIEnv *, jobject, jobject, jstring);

JNIEXPORT void  JNICALL Java_pers_zhc_tools_floatingdrawing_JNI_floatToByteArray
        (JNIEnv *, jobject, jbyteArray, jfloat, jint);

JNIEXPORT void  JNICALL Java_pers_zhc_tools_floatingdrawing_JNI_intToByteArray
        (JNIEnv *env, jobject obj, jbyteArray, jint j, jint);

JNIEXPORT jfloat JNICALL Java_pers_zhc_tools_floatingdrawing_JNI_byteArrayToFloat
        (JNIEnv *env, jobject obj, jbyteArray bytes, jint);

JNIEXPORT jint JNICALL Java_pers_zhc_tools_floatingdrawing_JNI_byteArrayToInt
        (JNIEnv *env, jobject obj, jbyteArray bytes, jint);

#ifdef __cplusplus
}
#endif
#endif
