/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_tools_floatingboard_JNI */

#ifndef _Included_com_zhc_tools_floatingboard_JNI
#define _Included_com_zhc_tools_floatingboard_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_tools_floatingboard_JNI
 * Method:    mV
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_zhc_tools_floatingboard_JNI_mG
  (JNIEnv *, jobject, jobject   );

#ifdef __cplusplus
}
#endif
#endif
