/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_tools_floatingboard_JNI */

#ifndef _Included_com_zhc_tools_floatingboard_JNI
#define _Included_com_zhc_tools_floatingboard_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_tools_floatingboard_JNI
 * Method:    mV
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_floatingboard_JNI_mG
        (JNIEnv *, jobject, jobject, jstring);

JNIEXPORT jbyteArray JNICALL Java_pers_zhc_tools_floatingboard_JNI_floatToByteArray
        (JNIEnv *, jobject, jfloat);

JNIEXPORT jbyteArray JNICALL Java_pers_zhc_tools_floatingboard_JNI_intToByteArray
        (JNIEnv *env, jobject obj, jint j);

JNIEXPORT jfloat JNICALL Java_pers_zhc_tools_floatingboard_JNI_byteArrayToFloat
        (JNIEnv *env, jobject obj, jbyteArray bytes);

JNIEXPORT jint JNICALL Java_pers_zhc_tools_floatingboard_JNI_byteArrayToInt
        (JNIEnv *env, jobject obj, jbyteArray bytes);

#ifdef __cplusplus
}
#endif
#endif
