/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Pi */

#ifndef _Included_pers_zhc_tools_jni_JNI_Pi
#define _Included_pers_zhc_tools_jni_JNI_Pi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Pi
 * Method:    gen
 * Signature: (ILpers/zhc/tools/pi/JNICallback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Pi_gen
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
