/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_FourierSeriesCalc */

#ifndef _Included_pers_zhc_tools_jni_JNI_FourierSeriesCalc
#define _Included_pers_zhc_tools_jni_JNI_FourierSeriesCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_FourierSeriesCalc
 * Method:    calc
 * Signature: (DILpers/zhc/tools/jni/JNI/FourierSeriesCalc/Callback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024FourierSeriesCalc_calc
  (JNIEnv *, jclass, jdouble, jint, jobject);

/*
 * Class:     pers_zhc_tools_jni_JNI_FourierSeriesCalc
 * Method:    nSetFunctionResult
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024FourierSeriesCalc_nSetFunctionResult
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
