/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_jni_JNI_Sqlite3 */

#ifndef _Included_pers_zhc_tools_jni_JNI_Sqlite3
#define _Included_pers_zhc_tools_jni_JNI_Sqlite3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    createHandler
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_createHandler
  (JNIEnv *, jclass);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    releaseHandler
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_releaseHandler
  (JNIEnv *, jclass, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    open
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_open
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     pers_zhc_tools_jni_JNI_Sqlite3
 * Method:    exec
 * Signature: (ILjava/lang/String;Lpers/zhc/tools/jni/JNI/Sqlite3/SqliteExecCallback;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_jni_JNI_00024Sqlite3_exec
  (JNIEnv *, jclass, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
