/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_codec_JNI */

#ifndef _Included_com_zhc_codec_JNI
#define _Included_com_zhc_codec_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_codec_JNI
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhc_tools_codecs_JNI_qmcDecode
        (JNIEnv *env, jobject obj, jstring f, jstring dF, jint mode);

/*
 * Class:     com_zhc_codec_JNI
 * Method:    kwmDecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhc_tools_codecs_JNI_kwmDecode
        (JNIEnv *env, jobject obj, jstring f, jstring dF, jint mode);

/*
 * Class:     com_zhc_base128_JNI
 * Method:    Base128_encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhc_tools_codecs_JNI_Base128_1encode
        (JNIEnv *env, jobject obj, jstring f1, jstring f2, jint mode);

/*
 * Class:     com_zhc_base128_JNI
 * Method:    Base128_decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhc_tools_codecs_JNI_Base128_1decode
        (JNIEnv *env, jobject obj, jstring f1, jstring f2, jint mode);


#ifdef __cplusplus
}
#endif
#endif
