/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_qmcflac_qmcflac_Decode_JNI */

#ifndef _Included_com_zhc_qmcflac_qmcflac_Decode_JNI
#define _Included_com_zhc_qmcflac_qmcflac_Decode_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_qmcflac_qmcflac_Decode_JNI
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhc_qmcflac_qmcflac_1Decode_JNI_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
