/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_codec_JNI */

#ifndef _Included_com_zhc_codec_JNI
#define _Included_com_zhc_codec_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_codec_JNI
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhc_JNI_qmcDecode
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_zhc_codec_JNI
 * Method:    kwmDecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhc_JNI_kwmDecode
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_zhc_base128_JNI
 * Method:    Base128_encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhc_JNI_Base128_1encode
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_zhc_base128_JNI
 * Method:    Base128_decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhc_JNI_Base128_1decode
        (JNIEnv *, jobject, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
