/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_tools_utils_BitmapUtil */

#ifndef _Included_pers_zhc_tools_utils_BitmapUtil
#define _Included_pers_zhc_tools_utils_BitmapUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_utils_BitmapUtil
 * Method:    getBitmapResolution
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_pers_zhc_tools_utils_BitmapUtil_getBitmapResolution
  (JNIEnv *env, jobject instance, jobject bitmap, jobject point);

#ifdef __cplusplus
}
#endif
#endif
